// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEwtqT-yfy2mB6LGIbnwH36sOCxzjfPwE',
    appId: '1:353346366076:web:62704033538703deb337f9',
    messagingSenderId: '353346366076',
    projectId: 'registration-backend-ddac4',
    authDomain: 'registration-backend-ddac4.firebaseapp.com',
    storageBucket: 'registration-backend-ddac4.firebasestorage.app',
    measurementId: 'G-3H79ST0Z16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSlgfmLQosOfZKdeX3OYy5qDsKcGEutTc',
    appId: '1:353346366076:android:5278be3c7da44d3fb337f9',
    messagingSenderId: '353346366076',
    projectId: 'registration-backend-ddac4',
    storageBucket: 'registration-backend-ddac4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxD7PpXCrOtkd6n3-ezT5MLnpXLJoZAUA',
    appId: '1:353346366076:ios:3975ca311a8bf924b337f9',
    messagingSenderId: '353346366076',
    projectId: 'registration-backend-ddac4',
    storageBucket: 'registration-backend-ddac4.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxD7PpXCrOtkd6n3-ezT5MLnpXLJoZAUA',
    appId: '1:353346366076:ios:3975ca311a8bf924b337f9',
    messagingSenderId: '353346366076',
    projectId: 'registration-backend-ddac4',
    storageBucket: 'registration-backend-ddac4.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEwtqT-yfy2mB6LGIbnwH36sOCxzjfPwE',
    appId: '1:353346366076:web:7818c3ff319f3ec2b337f9',
    messagingSenderId: '353346366076',
    projectId: 'registration-backend-ddac4',
    authDomain: 'registration-backend-ddac4.firebaseapp.com',
    storageBucket: 'registration-backend-ddac4.firebasestorage.app',
    measurementId: 'G-N45ESQBHSH',
  );
}
